export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  RECENTLY_PLAYED: '/recently-played',
  TRENDING: '/trending',
  NEW_RELEASES: '/new-releases',
  MUSIC: '/music',
  ORIGINALS: '/originals',
  SLOTS: '/slots',
  LIVE_CASINO: '/live-casino',
  GAME_SHOWS: '/game-shows',
  BLACKJACK: '/blackjack',
  BACCARAT: '/baccarat',
  ROULETTE: '/roulette',
  WEEKLY_RACES: '/weekly-races',
  WEEKLY_RACE: '/weekly-race',
  LEADERBOARD: '/leaderboard',
  CHALLENGES: '/challenges',
  VIP_REWARDS: '/vip-rewards',
  AFFILIATE: '/affiliate',
  BUY_COINS: '/buy-coins',
  PROVIDERS: '/providers',
  LIVE_SUPPORT: '/live-support',
  PROFILE: '/profile',
  SETTINGS: '/settings',
};
